import "./App.css";
import { Panel } from "./components/panel";
import { Lane, LaneContent, LaneFooter, LaneHeader } from "./components/lane";
import { Item } from "./components/item";

function App() {
  return (
    <>
      <div>
        <h3>Soy Un Panel</h3>
      </div>
      <Panel>
        <Lane>
          <LaneHeader>Carril 1</LaneHeader>
          <LaneContent>
            <Item>Shirley</Item>
            <Item>Edson</Item>
            <Item>Shirley</Item>
            <Item>Edson</Item>
            <Item>Shirley</Item>
            <Item>Edson</Item>
            <Item>Shirley</Item>
            <Item>Edson</Item>
            <Item>Shirley</Item>
            <Item>Edson</Item>
            <Item>Shirley</Item>
            <Item>Edson</Item>
            <Item>Shirley</Item>
            <Item>Edson</Item>
            <Item>Shirley</Item>
            <Item>Edson</Item>
            <Item>Shirley</Item>
            <Item>Edson</Item>
            <Item>Shirley</Item>
            <Item>Edson</Item>
          </LaneContent>
          <LaneFooter />
        </Lane>
        <Lane>
          <LaneHeader>Carril 2</LaneHeader>
          <LaneContent>
            <Item>Shirley</Item>
            <Item>Edson</Item>
            <Item>Shirley</Item>
            <Item>Edson</Item>
            <Item>Shirley</Item>
            <Item>Edson</Item>
            <Item>Shirley</Item>
            <Item>Edson</Item>
            <Item>Shirley</Item>
            <Item>Edson</Item>
            <Item>Shirley</Item>
            <Item>Edson</Item>
            <Item>Shirley</Item>
            <Item>Edson</Item>
            <Item>Shirley</Item>
            <Item>Edson</Item>
            <Item>Shirley</Item>
            <Item>Edson</Item>
            <Item>Shirley</Item>
            <Item>Edson</Item>
          </LaneContent>
          <LaneFooter />
        </Lane>
        {/* <Lane>
          <LaneHeader>
            Carril 3
          </LaneHeader>
          <LaneContent>
            <Item>
              Shirley
            </Item>
            <Item>
              Edson
            </Item>
            <Item>
              Shirley
            </Item>
            <Item>
              Edson
            </Item>
            <Item>
              Shirley
            </Item>
            <Item>
              Edson
            </Item>
            <Item>
              Shirley
            </Item>
            <Item>
              Edson
            </Item>
            <Item>
              Shirley
            </Item>
            <Item>
              Edson
            </Item>
            <Item>
              Shirley
            </Item>
            <Item>
              Edson
            </Item>
            <Item>
              Shirley
            </Item>
            <Item>
              Edson
            </Item>
            <Item>
              Shirley
            </Item>
            <Item>
              Edson
            </Item>
            <Item>
              Shirley
            </Item>
            <Item>
              Edson
            </Item>
            <Item>
              Shirley
            </Item>
            <Item>
              Edson
            </Item>
          </LaneContent>
           <LaneFooter/>
        </Lane>
        <Lane>
          <LaneHeader>
            Carril 4
          </LaneHeader>
          <LaneContent>
            <Item>
              Shirley
            </Item>
            <Item>
              Edson
            </Item>
            <Item>
              Shirley
            </Item>
            <Item>
              Edson
            </Item>
            <Item>
              Shirley
            </Item>
            <Item>
              Edson
            </Item>
            <Item>
              Shirley
            </Item>
            <Item>
              Edson
            </Item>
            <Item>
              Shirley
            </Item>
            <Item>
              Edson
            </Item>
            <Item>
              Shirley
            </Item>
            <Item>
              Edson
            </Item>
            <Item>
              Shirley
            </Item>
            <Item>
              Edson
            </Item>
            <Item>
              Shirley
            </Item>
            <Item>
              Edson
            </Item>
            <Item>
              Shirley
            </Item>
            <Item>
              Edson
            </Item>
            <Item>
              Shirley
            </Item>
            <Item>
              Edson
            </Item>
          </LaneContent>
           <LaneFooter/>
        </Lane> */}
      </Panel>
    </>
  );
}

export default App;
